# Generated by Django 3.1.7 on 2021-03-21 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_admin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
