# Generated by Django 3.1.7 on 2021-03-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='is_registered_admin',
            field=models.BooleanField(default=False),
        ),
    ]
